- name: lab-nginx
  hosts: localhost
  roles:
    - role: local.pegasuspad.docker
  tasks:
    - name: Start nginx container
      community.docker.docker_container:
        auto_remove: false
        detach: true
        env: {}
        exposed_ports:
          - "80"
          - "443"
        image: nginx
        name: nginx
        published_ports:
          - 80:80
          - 443:443
        restart_policy: always
        state: started
        # volumes:
        #   - /etc/nginx:/etc/nginx:ro
  vars:
    docker_backup_repository_password: test123
    